# Generated by Django 4.0.1 on 2022-01-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/R.0805d07b70205857a5d61233c4367aa3?rik=WiEAj2ucqd4%2bow&riu=http%3a%2f%2fwww.dirtyapronrecipes.com%2fwp-content%2fuploads%2f2015%2f10%2ffood-placeholder.png&ehk=%2fDEsN86Sice1qoWX66c3zxNDjukANZCb9EhIWD0PJP4%3d&risl=&pid=ImgRaw&r=0', max_length=500),
        ),
    ]
